# Site
title:              まことMACOTO
bio:                'まことmacotoOFFICIAL by yukiyuki'
description:        "まことmacotoOFFICIAL by yukiyuki"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://PICOPON.github.io" # the base hostname & protocol for your site

# Comments
disqus_shortname:   picopicopon

# Social
analytics-id:       "default"
twitter:            rnqq
facebook:           /
instagram:          /
github:             /

# personal
producer:           工具人yukionna
email:              1322363294@qq.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   https://tva1.sinaimg.cn/large/0081Kckwly1glmfy7b48qj31hc0u0kb6.jpg  #https://tva1.sinaimg.cn/large/0081Kckwly1glmjh1qsp3j31d80u04cl.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
